; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26730.0 

	TITLE	D:\Documents\CANADA\COURS\IA\Travaux\RavenProject\Sources\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
